# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)  # Enable verbose regex for better readability
  (src/bitbully/assets/book_12ply\.dat
   |src/bitbully/assets/book_12ply_distances\.dat)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ pre-push ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

      # Collides with clang-format
      # CMake formatting
      #- repo: https://github.com/cheshirekow/cmake-format-precommit
      #  rev: v0.6.13
      #  hooks:
      #    - id: cmake-format
      #      additional_dependencies: [ pyyaml ]
      #      types: [ file ]
      #      files: (\.cmake|CMakeLists.txt)(.in)?$
      # - id: cmake-lint
      #  additional_dependencies: [ pyyaml ]
      #  types: [ file ]
      #  files: (\.cmake|CMakeLists.txt)(.in)?$

  #  Suggested hook if you add a .clang-format file
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
