site_name: BitBully Docs
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate   # (optional) Enables annotation features for clarity
    - content.code.select
  code_copy:
    remove_prompts: true
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide: user_guide.md
  - BitBully API Reference:
      - bitbully: bitbully.md
      - board: board.md
      - gui_c4: gui_c4.md
      - bitbully_core: bitbully_core.md
  - Develop: develop.md
  - C++ Docs: cpp/html/index.html  # Link to Doxygen HTML docs


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- mkdocstrings

watch:
- src/bitbully/
- docs/
