[tool.commitizen]
version = "0.0.5" # Current version managed by Commitizen
version_files = ["version.h", "version.txt"] # Optional: if cz can directly bump it
post_bump_hooks = "./scripts/update_version.sh"
