name: Build

on:
  push:
    tags:
      - "v*"  # Runs only on new tags starting with 'v'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30 # Consider increasing timeout
    strategy:
      fail-fast: false
      matrix:
        # Add again, once repo is no longer private: ubuntu-24.04-arm
        os: [ ubuntu-latest, windows-latest, macos-13, macos-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: |
          python -m pip install build cibuildwheel==2.22.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.15"
          # ðŸ‘‡ Override build only for pre-releases
          CIBW_BUILD: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-') && 'cp311-*' || '' }}
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  # https://cibuildwheel.pypa.io/en/stable/deliver-to-pypi/
  upload_pypi:
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    #if: github.event_name == 'release' && github.event.action == 'published'
    # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      # Upload pre-releases to TestPyPI only
      - name: Publish to TestPyPI (pre-releases)
        if: contains(github.ref, 'a') || contains(github.ref, 'b') || contains(github.ref, 'rc') || contains(github.ref, 'dev')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: https://test.pypi.org/legacy/

      # publish to main PyPI
      - name: Publish to PyPI (stable releases)
        if: "!contains(github.ref, 'a') && !contains(github.ref, 'b') && !contains(github.ref, 'rc') && !contains(github.ref, 'dev')"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          # attestations: false # Turn attestations off in case of issues



  delete_artifacts:
    name: Delete unnecessary GitHub Artifacts
    runs-on: ubuntu-latest
    needs: [ build_wheels, build_sdist, upload_pypi ]
    if: always()  # Ensure this job always runs
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            cibw-wheels-*
            cibw-sdist
